pipeline:
  identifier: Build_k_iac_harness_1685989878210
  name: Build k-iac-harness
  orgIdentifier: default
  projectIdentifier: cicdharness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1685931527912
        repoName: muaminu/k-iac-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: Gcloud
                    host: gcr.io
                    projectID: us-gcp-ame-con-sjsxu-npd-1
                    imageName: Python_flasks_harness
                    tags:
                      - harnessbuild
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
